name: 'Linear Status Transition'
description: 'Transition lenear tickets status, adds labels'
author: '44pixels'

# Define your inputs here.
inputs:
  api_key:
    description: 'Linear Personal API key'
    required: true
  team_key:
    description: 'Linear team key, usually issues are created with team key prefix, e.g. CHAT-137'
    required: true
  issue_identifiers:
    description: 'One or more issues to update, for example see ./github/workflows/ci.yml'
    required: true
  add_labels:
    description: 'Labels names to add. Case sensitive.'
    required: false
  remove_labels:
    description: 'Labels names to remove. Case sensitive.'
    required: false
  transition_to:
    description: 'Name of the state you want issues to be transition to. Case sensitive.'
    required: true
  transition_from:
    description: 'Whitelist of statuses the transition is allowed from. Case sensitive.'
    required: false

runs:
  using: node20
  main: dist/index.js
